### PR TITLE
Feature/group increment

### PR DESCRIPTION
**Pull request by stefanrenne**
- Fixed Lint warnings
One left not sure how to resolve it
```
drivers/Zigbee2MQTTDevice.js
  266:14  error  Parsing error: Unexpected token .
```
- Fixed exposed capabilities not available for groups

### CODE REVIEW

**Comment by Vitaliy-Yakovchuk** [comment]
Yes, indeed the issue was I have groups with no devices

Found two more bugs with the groups support:

- If to change any settings of the group in homey (e.g. exclude from HomeKit), I'm getting the error:

image

- Colour lump mode is not supported (but that if probably because of my PR was merged in parallel with your work).


But in general it already works, already using this new groups feature!

**Comment by stefanrenne** [comment]
@Vitaliy-Yakovchuk i moved most of the device logic to a different file so big chance that I missed some stuff from your pr would you be able to help me out in finding where I missed your pr?

**Comment by Vitaliy-Yakovchuk** [comment]
I’d be happy to help and test; I just don’t know when, as my days have been quite busy.

**Comment by stefanrenne** [comment]
@Vitaliy-Yakovchuk  I found the issue related to not being able to modify settings, the issue was that the UID was an int and it should be stored as a string (like also is the case for devices), so that has now been resolved but the downside is that you have to re-add your groups

**Comment by gruijter** [comment]
@stefanrenne I merged and made some small changes/fixes again.

The use of optional chaining (?.) is not supported below NodeJS 13, and thus is incompatible with Homey Pro < 2023.
Furthermore, in Zigbee2MQTTdevice you have this:
`getDeviceInfo() { throw Error('getDeviceInfo is not implemented'); }`
If it is not implemented, why do you need it?

**Pull request merged**
